# Application name
spring.application.name=cricbuzz

# DataSource configuration
spring.datasource.url=mysql://root:YntSuTZztFmEAHPjgwwSyWIrLEKIsQyJ@kodama.proxy.rlwy.net:51305/railway
spring.datasource.username=root
spring.datasource.password=YntSuTZztFmEAHPjgwwSyWIrLEKIsQyJ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server configuration (optional)
server.port=8080

sportmonks.api.token=GrrZMZWLp184B67QLPEyscG7vLCfDoZFbwwuXHJ8MYbQ3Fc9lW1XpuUDusAo
sportmonks.base.url=https://cricket.sportmonks.com/api/v2.0

# SportMonks Free API
# sportmonks.api.token=YOUR_FREE_API_KEY
